### ISSUE TITLE
Swagger - Create Participant Swagger from Global

### ISSUE THREAD

**Issue by EkkeErick** [OpenBanking-Brasil/specs-directory#1]
Thread copied from e-mail:

Sammara (Infra WG): So Ralph we discussed within the Directory Squad team and we identified that the current swagger has many endpoints that won't be used by TTPs or ASPSP and would just expose the directory unnecessarily. 
And for that we understand it would be better if we have only the following endpoints at our public website:

•	Organisations
•	Organisations – Export
•	Webhooks
•	Authorisation Servers
•	Authorisation Servers – API Resources
•	Authorisation Servers - API Discovery Endpoints
•	Software Statements for an Organisation
•	Software Statement Certificates 
•	Software Statement Assertions 
•	Organisation Certificates

**Comment by EkkeErick** [comment]
Thread copied from e-mail:

Ralph (Raidiam): The other thing we need is a list of all endpoints and the keys that you want for fase 2.

E.g accounts-transactions where as previously you just had accounts with a big list of endpoints that can’t be searched for.

**Comment by sammaraferrao** [comment]
Thread copied from e-mail:

The APIs and endpoints are as Follows:

API | ENDPOINT
-- | --
Customers | customers/v1/personal/identifications
Customers | customers/v1/personal/qualifications
Customers | customers/v1/personal/finantial-relations
Customers | customers/v1/business/identifications
Customers | customers/v1/business/qualifications
Customers | customers/v1/business/finantial-relations
credit-cards-accounts | credit-cards-accounts/v1/accounts/{creditCardAccountId}
credit-cards-accounts | credit-cards-accounts/v1/accounts/{creditCardAccountId}/limits
credit-cards-accounts | credit-cards-accounts/v1/accounts/{creditCardAccountId}/transactions
credit-cards-accounts | credit-cards-accounts/v1/accounts/{creditCardAccountId}/bills
Accounts | accounts/v1/accounts
Accounts | accounts/v1/accounts/{accountId}
Accounts | accounts/v1/accounts/{accountId}/balances
Accounts | accounts/v1/accounts/{accountId}/overdraft-limits
loans | loans/v1/contract/{contractId}
loans | loans/v1/contract/{contractId}/warranties
loans | loans/v1/contract/{contractId}/payments
loans | loans/v1/contract/{contractId}/instalments
financings | financings/v1/contract/{contractId}
financings | financings/v1/contract/{contractId}/warranties
financings | financings/v1/contract/{contractId}/payments
financings | financings/v1/contract/{contractId}/instalments
unarranged-accounts-overdraft | unarranged-accounts-overdraft/v1/contract/{contractId}
unarranged-accounts-overdraft | unarranged-accounts-overdraft/v1/contract/{contractId}/warranties
unarranged-accounts-overdraft | unarranged-accounts-overdraft/v1/contract/{contractId}/payments
unarranged-accounts-overdraft | unarranged-accounts-overdraft/v1/contract/{contractId}/instalments
invoice-financings | invoice-financings/v1/contract/{contractId}
invoice-financings | invoice-financings/v1/contract/{contractId}/warranties
invoice-financings | invoice-financings/v1/contract/{contractId}/payments
invoice-financings | invoice-financings/v1/contract/{contractId}/instalments

**Comment by sammaraferrao** [comment]
**Radiam' Consideration:** 

Ok and if people implement say “accounts” they have to implement all of the endpoints? Or only some.  If it’s only some then the keys you want are by customer eg customer-personal, customer-business.

Ask yourself this question, as a tpp how do I find the endpoint for business accounts for banks that have business customers? In the above model I can’t without searching in all of the accounts endpoints for something that contains “business”.

This is doable, but is this what you want?

Is it worth a quick chat on this? I think what you have here are multiple “APIs” e.g The loans api has four endpoints but I’m assuming that banks that if the implement the loans api need to implement all endpoints?

So for loans you could  just advertise loans/v1/contract as the base path of the loans api.

Otherwise you are essentially reflecting every endpoint in the directory which is Ok too, but then every endpoint itself should have a specific key (which is what swagger has).

There’s no real right or wrong way here.

**Comment by sammaraferrao** [comment]
You really got me confused on this. A quick chat would be great! Maybe monday?

**Comment by RalphBragg** [comment]
@sammaraferrao  - can we schedule this chat please for tomorrow? Looking at the table above, the key 'Customers' wouldn't allow be determine if a bank supports business and retail customers. i would suggest splitting



API | ENDPOINT
-- | --
Customers-personal | customers/v1/personal/identifications
Customers-personal | customers/v1/personal/qualifications
Customers-personal | customers/v1/personal/finantial-relations
Customers-business | customers/v1/business/identifications
Customers-business | customers/v1/business/qualifications
Customers-business | customers/v1/business/finantial-relations

Also - we shouldn't be putting every endpoint in the directory, just the link to the Base Path of the API.

e.g

the Customers-personal API 
API | ENDPOINT
-- | --
Customers-personal | customers/v1/personal/identifications
Customers-personal | customers/v1/personal/qualifications
Customers-personal | customers/v1/personal/finantial-relations

But listed on the directory should be
API | API BasePath
-- | --
Customers-personal | customers/v1/personal
Customers-business | customers/v1/business
